---
# Handlers for the hadoop master services

- name: restart hadoop master services
  service: name=${item} state=restarted
  with_items: 
    - hadoop-0.20-mapreduce-jobtracker
    - hadoop-0.20-namenode

- name: restart hadoopha master services
  service: name=${item} state=restarted
  with_items: 
    - hadoop-0.20-mapreduce-jobtrackerha
    - hadoop-0.20-namenode
